using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SIMULTAN.Serializer.DXF
{
    // [0    - 1000]: DXF Specs and general custom codes
    // [1001 - 1100]: Parameter
    // [1101 - 1300]: MultiValue
    // [1301 - 1400]: Calculation
    // [1401 - 1500]: Component
    //      [[1421 - 1430]]: Component -> AccessTracker
    //      [[1431 - 1440]]: Component -> AccessProfile
    //      [[1451 - 1460]]: TypedComponent
    // [1501 - 1600]: FlowNetwork
    // [1601 - 1700]: GeometicRelationship
    // [1701 - 1800]: Mapping2Component
    // [5001 - 5050]: Important Parameter visualizations
    // [6001 - 7000]: Excel Mapping
    // [7001 - 8000]: Assets
    // [8001 - 9000]: ChatItmes
    // [9001 - 10000]: Users
    // [20001 - 21000]: HierarchicalProjects
    // [21001 - 22000]: UserComponentList

    public enum ComponentSaveCode
    {
        NAME = 1401,
        DESCRIPTION = 1402,
        CATEGORY = 1403,                    // as string
        ACCESS_RECORD = 1404,               // NOT USED -> saved as DXF Entities within a DXF entity
        [Obsolete("Only FUNCTION_SLOT_CURRENT is in use")]
        FUNCTION_SLOTS_ALL = 1405,          // as a sequence of strings
        FUNCTION_SLOT_CURRENT = 1406,

        CONTAINED_COMPONENTS = 1407,        // saved as DXF Entities
        CONTAINED_COMPONENT_SLOTS = 1408,   // saved as a sequence of strings
        REFERENCED_COMPONENTS = 1409,       // saved as pairs of STRING and LONG
        CONTAINED_PARAMETERS = 1410,        // saved as DXF Entities
        CONTAINED_CALCULATIONS = 1411,      // saved as DXF Entities

        [Obsolete]
        TIME_STAMP = 1412,
        SYMBOL_ID = 1413,
        RELATIONSHIPS_TO_GEOMETRY = 1414,   // saved as DXF Entities
        INSTANCE_TYPE = 1428,               // InstanceType
        GENERATED_AUTOMATICALLY = 1415,     // from exchange with the GeometryViewer
        MAPPINGS_TO_COMPONENTS = 1416,      // for deferred calculations
        [Obsolete]
        REFERENCES_INTACT = 1417,           // in case references were removed and the user with writing access does not accept or agree
        MAPPINGS_TO_EXCEL_TOOLS = 1418,

        VISIBILTY = 1419,                   // in projects
        COLOR = 1420,                       // for the new interface
        SORTING_TYPE = 1421                 // for the sub-components
    }

    //      [[1451 - 1460]]: TypedComponent
    public enum TypedComponentSaveCode
    {
        TYPE_NAME = 1451,
        TYPE_VALIDATOR_NAME = 1452
    }

    public enum ComponentAccessTrackerSaveCode
    {
        FLAGS = 1421,
        WRITE_PREV = 1422,
        WRITE_LAST = 1423,
        SUPERVIZE_PREV = 1424,
        SUPERVIZE_LAST = 1425,
        RELEASE_PREV = 1426,
        RELEASE_LAST = 1427
    }

    public enum ComponentAccessProfileSaveCode
    {
        STATE = 1431,
        PROFILE = 1432,
        MANAGER = 1433,

        ACTION_TARGET_ID = 1434,
        ACTION_SUPERVIZE = 1435,
        ACTION_RELEASE = 1436,
        ACTION_TIME_STAMP = 1437,
        ACTION_ACTOR = 1438
    }

    // [1001 - 1100]
    public enum ParameterSaveCode
    {
        NAME = 1001,
        UNIT = 1002,
        CATEGORY = 1003,
        PROPAGATION = 1004,
        INSTANCE_PROPAGATION = 1014,

        VALUE_MIN = 1005,
        VALUE_MAX = 1006,
        VALUE_CURRENT = 1007,
        [Obsolete]
        IS_WITHIN_BOUNDS = 1008,

        // VALUE_FIELD is saved in a separate file
        VALUE_FIELD_REF = 1009,
        // VALUE_FIELD_POINTER -> see MultiValueSaveCode

        VALUE_TEXT = 1010,

        [Obsolete]
        IS_IMPORTANT = 1011, // for the user
        ALLOWED_OPERATIONS = 1012,

        IS_AUTOGENERATED = 1013,
    }

    // [1101 - 1300]
    public enum MultiValueSaveCode
    {
        MVType = 1101,
        MVCanInterpolate = 1102,
        MVName = 1103,

        MVDisplayVector_NUMDIM = 1200,
        MVDisplayVector_CELL_INDEX_X = 1201, //Old
        MVDisplayVector_CELL_INDEX_Y = 1202, //Old
        MVDisplayVector_CELL_INDEX_Z = 1203, //Old
        MVDisplayVector_CELL_INDEX_W = 1204, //Old
        MVDisplayVector_POS_IN_CELL_REL_X = 1205, //Old
        MVDisplayVector_POS_IN_CELL_REL_Y = 1206, //Old
        MVDisplayVector_POS_IN_CELL_REL_Z = 1207, //Old
        MVDisplayVector_POS_IN_CELL_ABS_X = 1208, //Old
        MVDisplayVector_POS_IN_CELL_ABS_Y = 1209, //Old
        MVDisplayVector_POS_IN_CELL_ABS_Z = 1210, //Old
        MVDisplayVector_VALUE = 1211, //Old
        MVDisplayVector_CELL_SIZE_W = 1212, //Old
        MVDisplayVector_CELL_SIZE_H = 1213, //Old

        MVDisplayVector_GRAPH_NAME = 1214,
        MVDisplayVector_AXIS_VAL_X = 1215,
        MVDisplayVector_AXIS_VAL_Y = 1216,
        MVDisplayVector_AXIS_VAL_Z = 1217,
        MVDisplayVector_MVID = 1218,
        MVDisplayVector_MVLOCATION = 1219,

        MVUnitX = 1104,
        MVUnitY = 1105,
        MVUnitZ = 1106,

        NrX = 1107,
        MinX = 1108,
        MaxX = 1109,

        NrY = 1110,
        MinY = 1111,
        MaxY = 1112,

        NrZ = 1113,
        MinZ = 1114,
        MaxZ = 1115,

        XS = 1116,
        YS = 1117,
        ZS = 1118,

        FIELD = 1119,
        ROW_NAMES = 1120,

        ADDITIONAL_INFO = 1121,
        MVBT_COMPLETE_VALUE_ROW = 1122,

        ROW_UNITS = 1123,
    }

    // [1301 - 1400]
    public enum CalculationSaveCode
    {
        NAME = 1301,
        EXPRESSION = 1302,
        PARAMS_INPUT = 1303,
        PARAMS_OUTPUT = 1304,
        [SaveCodeNotInUse("Removed during refactoring since calculations do not store parameter names anymore")]
        LOST_REFS = 1305,
        [SaveCodeNotInUse("Removed during refactoring since calculations do not store parameter names anymore")]
        LOST_REFS_MSG = 1306,
        VECTOR_CALC_OPERATIONS = 1307,
        VECTOR_CALC_RANGES = 1308,
        VECTOR_CALC_NR_EXEC = 1309,
        VECTOR_CALC_AVERAGE = 1310,
        VECTOR_CALC_RANDOM = 1311,
        VECTOR_CALC_OVERRIDE = 1312
    }

    // [1501 - 1600]
    public enum FlowNetworkSaveCode
    {
        CONTENT_ID = 1501,      // local id of associated component, otherwise -1
        IS_VALID = 1502,
        POSITION_X = 1503,
        POSITION_Y = 1504,
        START_NODE = 1505,      // only SimFlowNetworkEdge: id of node
        END_NODE = 1506,        // only SimFlowNetworkEdge: id of node
        NAME = 1507,
        DESCRIPTION = 1508,
        MANAGER = 1509,
        [Obsolete]
        TIMESTAMP = 1510,
        CONTAINED_NODES = 1511, // only FlowNetwork: saved as DXF Entities
        CONTAINED_EDGES = 1512, // only FlowNetwork: saved as DXF Entities
        CONTIANED_NETW = 1513,  // only FlowNetwork: saved as DXF Entities
        NODE_SOURCE = 1514,     // only FlowNetwork (id of the start node)
        NODE_SINK = 1515,       // only FlowNetwork (id of the end node)
        CALC_RULES = 1516,
        CALC_RULE_SUFFIX_OPERANDS = 1517,
        CALC_RULE_SUFFIX_RESULT = 1518,
        CALC_RULE_DIRECTION = 1519,
        CALC_RULE_OPERATOR = 1520,
        GEOM_REP = 1521,        // only FlowNetwork (resource index of the geometry file representing the NW)
        GEOM_REP_NE_FILE_INDEX = 1531, // SimFlowNetworkElement: representation file index
        GEOM_REP_NE_GEOM_ID = 1532,     // SimFlowNetworkElement: representation geometry object id
        IS_DIRECTED = 1533,      // only FlowNetwork: indicates if the direction of the edges should be taken into account
        CONTENT_LOCATION = 1534  // global id of associated component, otherwise Guid.Empty
    }

    // [1601 - 1700]
    public enum ComponentInstanceSaveCode
    {
        NAME = 1601,
        STATE_TYPE = 1602,
        STATE_ISREALIZED = 1609,
        GEOM_IDS_X = 1603,
        GEOM_IDS_Y = 1604,
        GEOM_IDS_Z = 1605,
        GEOM_IDS_W = 1630,
        GEOM_CS = 1606,
        TRANSF_WC2LC = 1607,
        TRANSF_LC2WC = 1608,
        INST_ROTATION = 1619,
        INST_SIZE = 1620,
        INST_NWE_ID = 1621,
        INST_NWE_NAME = 1622,
        INST_PATH = 1623,
        INST_SIZE_TRANSSETTINGS = 1640,
        INST_SIZE_TS_SOURCE = 1641,
        INST_SIZE_TS_INITVAL = 1642,
        INST_SIZE_TS_PARAMETER = 1643,
        INST_SIZE_TS_CORRECT = 1644,
        INST_PARAMS = 1650,
        INST_PARAM_KEY = 1651,
        INST_PARAM_VAL = 1652,
        INST_REFS = 1660,
        INST_REFS_KEY = 1661,
        INST_REFS_VAL = 1662,
        GEOM_REF_FILE = 1663,
        GEOM_REF_ID = 1664,
        STATE_CONNECTION_STATE = 1665,
        INST_NWE_LOCATION = 1666,
        INST_PROPAGATE_PARAM_CHANGES = 1667
    }

    public enum Mapping2ComponentSaveCode
    {
        NAME = 1701,
        CALCULATOR = 1702,
        INPUT_MAPPING = 1703,
        INPUT_MAPPING_KEY = 1704,
        INPUT_MAPPING_VALUE = 1705,
        OUTPUT_MAPPING = 1706,
        OUTPUT_MAPPING_KEY = 1707,
        OUTPUT_MAPPING_VALUE = 1708
    }

    public enum ComponentFileMetaInfoSaveCode
    {
        MAX_CALCULATION_ID = 1801,
    }

    // [5001 - 5050]
    public enum ImportantParamVisSaveCode
    {
        ID = 5001,
        POSITION_X = 5002,
        POSITION_Y = 5003,
        COLOR_R = 5004,
        COLOR_G = 5005,
        COLOR_B = 5006,
        COLOR_A = 5007,
        INDEX = 5008
    }

    // [6001 - 7000]: Excel Mapping
    public enum ExcelMappingSaveCode
    {
        RULE_NODE_NAME = 6001,
        RULE_SHEET_NAME = 6002,
        RULE_OFFSET_FROM_PARENT_X = 6003,
        RULE_OFFSET_FROM_PARENT_Y = 6004,
        RULE_SUBJECT = 6005,
        RULE_PROPERTIES = 6006,
        RULE_ACCEPT_MULTI_VAL_PER_PROPERTY = 6007,
        RULE_ORDER_HORIZONTALLY = 6008,
        RULE_PREPEND_CONTENT_TO_CHILDREN = 6009,
        RULE_FILTER = 6010,
        RULE_OFFSET_BTW_APPLICATIONS_X = 6011,
        RULE_OFFSET_BTW_APPLICATIONS_Y = 6012,
        RULE_CHILDREN = 6013,

        TOOL_NAME = 6101,
        TOOL_MACRO_NAME = 6102,
        TOOL_RULES = 6103,
        TOOL_LAST_PATH_TO_FILE = 6104,
        TOOL_RESULTS = 6105,
        TOOL_RESULT_UNMAPPINGS = 6106,

        MAP_PATH = 6201,
        MAP_TOOL_NAME = 6202,
        MAP_TOOL_FILE_PATH = 6203,
        MAP_RULE_NAME = 6204,
        MAP_RULE_INDEX = 6205,

        MAP_COL_OWNER_ID = 6301,
        MAP_COL_OWNER_MANAGER = 6302,
        MAP_COL_RULES = 6303,
        [Obsolete]
        MAP_COL_TODO = 6304,

        DATA_MAP_SHEET_NAME = 6501,
        DATA_MAP_RANGE_X = 6502,
        DATA_MAP_RANGE_Y = 6503,
        DATA_MAP_RANGE_Z = 6504,
        DATA_MAP_RANGE_W = 6505,
        DATA_MAP_TYPE = 6506,

        UNMAP_FILTER_SWITCH = 6521,
        UNMAP_TARGET_COMP_ID = 6522,
        UNMAP_TARGET_PARAM = 6523,
        UNMAP_FILTER_COMP = 6524,
        UNMAP_FILTER_PARAM = 6525,
        UNMAP_PARAM_POINTER_X = 6526,
        UNMAP_PARAM_POINTER_Y = 6527,
        UNMAP_DATA = 6528,
        UNMAP_TARGET_COMP_LOCATION = 6529,

        TRAVERSE_MAX_ELEM = 6601,
        TRAVERSE_MAX_LEVELS = 6602,
        TRAVERSE_STRATEGY = 6603,
        TRAVERSAL_ACTIVATED = 6604,

        VERSION = 6701
    }

    /// <summary>
    /// Mixes resource and asset save codes. Does not handle resources as objects.
    /// </summary>
    public enum AssetSaveCode
    {
        PATH_CODE = 7001,
        CONTENT_ID = 7002,
        REFERENCE_COL = 7003,
        REFERENCE = 7004,

        /// <summary>
        /// The absolute path to the working directory. Generally gets overriden on load.
        /// </summary>
        WORKING_DIR = 7090,
        /// <summary>
        /// The absolute fallback paths where to look for linked resources.
        /// </summary>
        WORKING_PATHS = 7091,

        /// <summary>
        /// The number of top-level resources contained in the asset manager.
        /// </summary>
        APATH_COLLECTION = 7101,
        /// <summary>
        /// The user who created the resource.
        /// </summary>
        APATH_USER = 7102,
        /// <summary>
        /// The integer key of the resource.
        /// </summary>
        APATH_KEY = 7103,
        /// <summary>
        /// The relative path to the resource (from the working dir or one of the fallback paths).
        /// </summary>
        APATH_REL_PATH = 7104,
        /// <summary>
        /// Indicates whether the resource is contained within a project or not.
        /// </summary>
        APATH_ISCONTAINED = 7105,
        /// <summary>
        /// The absolute path to the resource. Should be removed later.
        /// </summary>
        APATH_FULL_PATH = 7106,
        /// <summary>
        /// A boolean value indicating whether the resources are saved as objects or as a simple list.
        /// </summary>
        APATHS_AS_OBJECTS = 7107,
        /// <summary>
        /// The start of the asset collection. Indicates their number.
        /// </summary>
        ASSET_COLLECTION = 7111
    }

    /// <summary>
    /// Strictly for resource serialization as objects. Assets not included.
    /// </summary>
    public enum ResourceSaveCode
    {
        RESOURCE_USER = 7201,
        RESOURCE_KEY = 7202,
        RESOURCE_NAME = 7203,
        RESOURCE_RELATIVE = 7204,
        RESOURCE_ANCHOR = 7205,
        RESOURCE_FULL = 7206,
        RESOURCE_CHILDREN = 7207,
        RESOURCE_PROBLEM = 7208,

        RESOURCE_HAS_PARENT = 7211,
        RESOURCE_VISIBILITY = 7212
    }

    public enum ChatItemSaveCode
    {
        TYPE = 8001,
        AUTHOR = 8002,
        VR_ADDRESS = 8003,
        VR_PASSWORD = 8004,
        GIT_COMMIT = 8005,
        TIMESTAMP = 8006,
        MESSAGE = 8007,
        STATE = 8008,
        EXPECTED_REACTIONS_FROM = 8009,
        CHILDREN = 8010,

        CONVERSATION = 8101
    }

    public enum UserSaveCode
    {
        USER_ID = 9001,
        USER_NAME = 9002,
        USER_PSW_HASH = 9003,
        USER_ROLE = 9004,
        USER_ENCRYPTION_KEY = 9005,
    }

    public enum GeoMapSaveCode
    {
        MAP_PATH = 10001,
        GEOREFS = 10002,
        IMAGEPOS_X = 10003,
        IMAGEPOS_Y = 10004,
        LONGITUDE = 10005,
        LATITUDE = 10006,
        HEIGHT = 10007
    }

    public enum SitePlannerSaveCode
    {
        GEOMAPS = 11001,
        GEOMAP_PATH = 11002,
        BUILDINGS = 11003,
        BUILDING_INDEX = 11004,
        BUILDING_GEOMETRYMODEL_PATH = 11005,
        BUILDING_CUSTOM_COLOR = 11006,
        BUILDING_ID = 11007,
        ELEVATION_PROVIDER_TYPE = 11008,
        GRID_CELL_SIZE = 11009,
        VALUE_MAPPING_INDEX_USAGE = 11010,
        VALUE_MAPPING_COLOR_MAP_TYPE = 11011,
        VALUE_MAPPING_COLOR_MAP_PARAMS = 11012,
        VALUE_MAPPING_PREFILTER_TYPE = 11013,
        VALUE_MAPPING_PREFILTER_PARAMS = 11014,
        VALUE_MAPPING_VALUE_TABLE_KEY = 11015,
        VALUE_MAPPING_ASSOCIATIONS = 11016,
        VALUE_MAPPING_ASSOCIATION_INDEX = 11017,
        VALUE_MAPPING_ASSOCIATION_NAME = 11018,
        VALUE_MAPPING_ACTIVE_ASSOCIATION_INDEX = 11019,
        VALUE_MAPPING_VALUE_TABLE_LOCATION = 11020,
    }

    public enum ProjectSaveCode
    {
        PROJECT_ID = 200001,
        [Obsolete]
        NAME_OF_PUBLIC_VALUE_FILE = 200002,
        [Obsolete]
        NAME_OF_PUBLIC_COMPS_FILE = 200003,
        NR_OF_CHILD_PROJECTS = 200004,
        CHILD_PROJECT_ID = 200005,
        CHILD_PROJECT_REL_PATH = 200006
    }

    // [21001 - 22000]: UserComponentList
    public enum UserComponentListSaveCode
    {
        NAME = 21001,
        NR_OF_ROOT_COMPONENTS = 21002
    }
}
